//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Business_Target_Assign = new HashSet<Business_Target_Assign>();
            this.Tariff = new HashSet<Tariff>();
        }
    
        public string email { get; set; }
        public string admin_password { get; set; }
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string contact_no { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual ICollection<Business_Target_Assign> Business_Target_Assign { get; set; }
        public virtual ICollection<Tariff> Tariff { get; set; }
    }
}
