//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCItemEntry
    {
        public int ID { get; set; }
        public Nullable<int> AMCID { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string Name { get; set; }
        public string Existing_Ser { get; set; }
    }
}
