//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_users
    {
        public int b_user_id { get; set; }
        public string b_user_name { get; set; }
        public string b_user_password { get; set; }
        public string b_email { get; set; }
        public string b_Contact_no { get; set; }
        public System.DateTime c_date { get; set; }
        public bool active { get; set; }
    }
}
