//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Target_Assign
    {
        public int Assign_id { get; set; }
        public int b_Target_id { get; set; }
        public int user_id { get; set; }
        public int assign_by { get; set; }
        public Nullable<System.DateTime> assign_date { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
