//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_ProductOrder
    {
        public int business_id { get; set; }
        public int order_id { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public string PONO { get; set; }
    }
}
