//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business_Pics
    {
        public int business_pic_id { get; set; }
        public int business_id { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> enable { get; set; }
    }
}
