//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class business_ServiceHierarchy
    {
        public int ServiceHeirarchyID { get; set; }
        public Nullable<int> ParentServiceID { get; set; }
        public Nullable<int> ChildServiceID { get; set; }
        public Nullable<System.DateTime> EstDate { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> businessId { get; set; }
    }
}
