//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMaster
    {
        public CategoryMaster()
        {
            this.BrandMaster = new HashSet<BrandMaster>();
            this.BrandMaster1 = new HashSet<BrandMaster>();
            this.BrandMaster2 = new HashSet<BrandMaster>();
            this.BrandMaster3 = new HashSet<BrandMaster>();
            this.BrandMaster4 = new HashSet<BrandMaster>();
            this.BrandMaster5 = new HashSet<BrandMaster>();
            this.BrandMaster6 = new HashSet<BrandMaster>();
            this.BrandMaster7 = new HashSet<BrandMaster>();
            this.BrandMaster8 = new HashSet<BrandMaster>();
            this.BrandMaster9 = new HashSet<BrandMaster>();
            this.BrandMaster10 = new HashSet<BrandMaster>();
            this.BrandMaster11 = new HashSet<BrandMaster>();
            this.ProductsMaster = new HashSet<ProductsMaster>();
        }
    
        public int Categoryid { get; set; }
        public string Categoryname { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Createby { get; set; }
        public string Updateby { get; set; }
        public System.DateTime Createdate { get; set; }
        public System.DateTime Updatedate { get; set; }
        public Nullable<int> ShopID { get; set; }
        public string CategoryMessage { get; set; }
    
        public virtual ICollection<BrandMaster> BrandMaster { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster1 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster2 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster3 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster4 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster5 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster6 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster7 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster8 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster9 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster10 { get; set; }
        public virtual ICollection<BrandMaster> BrandMaster11 { get; set; }
        public virtual ICollection<ProductsMaster> ProductsMaster { get; set; }
    }
}
