//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLogin
    {
        public int Client_login_id { get; set; }
        public string Client_id { get; set; }
        public string Client_password { get; set; }
        public Nullable<System.TimeSpan> Client_login_time { get; set; }
        public string browser { get; set; }
        public string os { get; set; }
        public string ip_address { get; set; }
        public string type { get; set; }
    }
}
