//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintResolutionStatus
    {
        public int StatusID { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
