//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintAttachment
    {
        public int AttachID { get; set; }
        public Nullable<int> RefID { get; set; }
        public string AttachDescription { get; set; }
        public string FiName { get; set; }
    }
}
