//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintStatus
    {
        public int StatusID { get; set; }
        public string StatusDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Shopid { get; set; }
        public Nullable<int> TimeDuration { get; set; }
        public Nullable<int> FeedSetting1 { get; set; }
        public Nullable<int> FeedSetting2 { get; set; }
        public Nullable<int> FeedSetting3 { get; set; }
        public Nullable<int> FeedSetting4 { get; set; }
        public Nullable<int> FeedSetting5 { get; set; }
        public Nullable<int> ProductCategoryid { get; set; }
    }
}
