//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerComplaint
    {
        public int CompID { get; set; }
        public string CompalintID { get; set; }
        public Nullable<System.DateTime> ComplaintDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ResolutionStatus { get; set; }
        public Nullable<System.TimeSpan> CompStartTime { get; set; }
        public Nullable<System.TimeSpan> CompEndTime { get; set; }
        public Nullable<int> SubmittedBY { get; set; }
        public string ReferenceNo { get; set; }
        public string ComplaintType { get; set; }
        public Nullable<int> ComplaintLogType { get; set; }
        public Nullable<System.DateTime> ServiceDueDate { get; set; }
        public Nullable<System.DateTime> ActualServiceDate { get; set; }
        public bool PayStatus { get; set; }
        public Nullable<int> PrevDuePaid { get; set; }
        public Nullable<int> CurrentChargePaid { get; set; }
        public int PaidAmt { get; set; }
        public int BalAmt { get; set; }
        public string ProductModelNo { get; set; }
        public Nullable<System.DateTime> ProductExpDate { get; set; }
        public Nullable<int> WarantyStatus { get; set; }
        public Nullable<int> HappyCode { get; set; }
        public Nullable<int> NextService_CatID { get; set; }
    }
}
