//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        public CustomerMaster()
        {
            this.CustomerMapping = new HashSet<CustomerMapping>();
            this.UserMaster = new HashSet<UserMaster>();
        }
    
        public int Customerid { get; set; }
        public string Customername { get; set; }
        public string City { get; set; }
        public string States { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Emailid { get; set; }
        public string Contact { get; set; }
        public string AltContact { get; set; }
        public string Address { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Createby { get; set; }
        public System.DateTime Createdate { get; set; }
        public string Updateby { get; set; }
        public System.DateTime Updatedate { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> AniversaryDate { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Gender { get; set; }
        public string StateCode { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingStateCode { get; set; }
        public string ShippingPinCode { get; set; }
        public string ShippingCountry { get; set; }
        public bool SameAsBilling { get; set; }
        public string Cardnumber { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public Nullable<int> CustomerType { get; set; }
        public string GSTIN1 { get; set; }
    
        public virtual ICollection<CustomerMapping> CustomerMapping { get; set; }
        public virtual ICollection<UserMaster> UserMaster { get; set; }
    }
}
