//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Attendance
    {
        public int attendance_id { get; set; }
        public int business_id { get; set; }
        public int Emp_id { get; set; }
        public Nullable<System.TimeSpan> Chk_In_Time { get; set; }
        public Nullable<System.TimeSpan> Chk_Out_Time { get; set; }
        public Nullable<System.DateTime> Att_Date { get; set; }
        public string remarks { get; set; }
    }
}
