//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Salary
    {
        public int Salary_id { get; set; }
        public int Emp_id { get; set; }
        public int business_id { get; set; }
        public int emp_type { get; set; }
        public int Salary_type { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> Percentage { get; set; }
    }
}
