//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesMaster
    {
        public int Employeeid { get; set; }
        public string Employeename { get; set; }
        public string City { get; set; }
        public string States { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public string Emailid { get; set; }
        public string Contact { get; set; }
        public string AltContact { get; set; }
        public string Address { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Createby { get; set; }
        public System.DateTime Createdate { get; set; }
        public string Updateby { get; set; }
        public System.DateTime Updatedate { get; set; }
        public Nullable<int> ShopID { get; set; }
    }
}
