//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttandance
    {
        public Nullable<int> shopid { get; set; }
        public int attid { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<System.DateTime> empintime { get; set; }
        public Nullable<System.DateTime> empouttime { get; set; }
        public bool isactive { get; set; }
        public System.DateTime createdate { get; set; }
        public System.DateTime updatedate { get; set; }
    }
}
