//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        public EndUser()
        {
            this.Review_reply = new HashSet<Review_reply>();
        }
    
        public int Enduser_id { get; set; }
        public Nullable<int> business_id { get; set; }
        public string Enduser_name { get; set; }
        public string Enduser_password { get; set; }
        public string email { get; set; }
        public string Contact_no { get; set; }
        public Nullable<System.DateTime> c_date { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> city_Id { get; set; }
        public Nullable<int> location_Id { get; set; }
        public string profie_pic { get; set; }
        public Nullable<int> type { get; set; }
        public string Login_type { get; set; }
        public string gender { get; set; }
        public string code { get; set; }
        public string lname { get; set; }
        public Nullable<int> ms { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> anidate { get; set; }
        public string m_um { get; set; }
        public string Allergies { get; set; }
    
        public virtual ICollection<Review_reply> Review_reply { get; set; }
    }
}
