//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        public string enquiry_type { get; set; }
        public int enquiry_id { get; set; }
        public string enquiry_Name { get; set; }
        public bool active { get; set; }
        public int spend { get; set; }
    }
}
