//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryDetails
    {
        public int EnqID { get; set; }
        public string EnquiryID { get; set; }
        public Nullable<System.DateTime> EnquiryDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> FollowupDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ResolutionStatus { get; set; }
    }
}
