//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class fabkut_Static_cms
    {
        public int cms_id { get; set; }
        public string franchisee_content { get; set; }
        public string Inventory_content { get; set; }
        public string Customer_content { get; set; }
        public string Appointment_content { get; set; }
        public string Reports_content { get; set; }
        public string Billing_content { get; set; }
        public string Membership_content { get; set; }
        public string Marketing_content { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
