//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int facility_id { get; set; }
        public string facility_code { get; set; }
        public string facility_Name { get; set; }
        public string service_detail { get; set; }
        public bool active { get; set; }
    }
}
