//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemServiceCharge
    {
        public int ItemSerID { get; set; }
        public Nullable<int> Complainid { get; set; }
        public string CompalinNo { get; set; }
        public string ServiceID { get; set; }
        public string ServiceCharge { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createdate { get; set; }
        public System.DateTime Updatedate { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> TotalCharge { get; set; }
    }
}
