//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerTransaction
    {
        public int TranID { get; set; }
        public Nullable<int> RetailerID { get; set; }
        public string LedgNO { get; set; }
        public string PayType { get; set; }
        public Nullable<System.DateTime> PayDt { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> SupID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> EMPID { get; set; }
        public string Remark { get; set; }
        public bool ISActive { get; set; }
    }
}
