//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        public int id { get; set; }
        public string ModuleName { get; set; }
        public string MenuItemID { get; set; }
        public Nullable<int> Parentid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Shopid { get; set; }
    }
}
