//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferTermsMaster
    {
        public OfferTermsMaster()
        {
            this.fabkut_Offers_terms_conditions = new HashSet<fabkut_Offers_terms_conditions>();
        }
    
        public int OfferTermId { get; set; }
        public string OfferTermName { get; set; }
        public string OfferTermDescription { get; set; }
        public Nullable<int> fabkut_offer_id { get; set; }
    
        public virtual ICollection<fabkut_Offers_terms_conditions> fabkut_Offers_terms_conditions { get; set; }
    }
}
