//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferInvitation
    {
        public int AutoID { get; set; }
        public Nullable<int> fabkut_offer_id { get; set; }
        public Nullable<int> Business_id { get; set; }
        public Nullable<int> EnduserId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> sendDate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> Mess { get; set; }
    }
}
