//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsMaster
    {
        public ProductsMaster()
        {
            this.PurchaseItemDetail = new HashSet<PurchaseItemDetail>();
        }
    
        public int Productid { get; set; }
        public Nullable<int> CategoryProductId { get; set; }
        public Nullable<int> BrandProductId { get; set; }
        public string Productname { get; set; }
        public Nullable<int> Unit { get; set; }
        public string HSNCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Createby { get; set; }
        public string Updateby { get; set; }
        public System.DateTime Createdate { get; set; }
        public System.DateTime Updatedate { get; set; }
        public Nullable<int> Price { get; set; }
        public string Barcode { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> ShopID { get; set; }
        public string ImageName { get; set; }
        public string ModelNO { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
    
        public virtual BrandMaster BrandMaster { get; set; }
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
        public virtual ICollection<PurchaseItemDetail> PurchaseItemDetail { get; set; }
    }
}
