//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proofdetails
    {
        public int Proofid { get; set; }
        public string Proofname { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
