//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSrNoDetails
    {
        public int PurSrNoID { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<int> said { get; set; }
        public string SerielNumber { get; set; }
        public Nullable<int> Qty { get; set; }
        public bool IsSale { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createdate { get; set; }
        public System.DateTime Updatedate { get; set; }
    }
}
