//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewPics
    {
        public int review_id { get; set; }
        public Nullable<int> reviewPic_id { get; set; }
        public byte[] reviewPics1 { get; set; }
    }
}
