//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesItemDetail
    {
        public int SItmID { get; set; }
        public Nullable<int> SAID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public string HSNCode { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Shopid { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<bool> IncludingTax { get; set; }
        public string ModelNO { get; set; }
        public string ItemSrNo { get; set; }
        public Nullable<decimal> CGSTPer { get; set; }
        public Nullable<decimal> SGSTPer { get; set; }
        public Nullable<decimal> IGSTPer { get; set; }
        public Nullable<decimal> CGSTAmt { get; set; }
        public Nullable<decimal> SGSTAmt { get; set; }
        public Nullable<decimal> IGSTAmt { get; set; }
        public Nullable<decimal> NetTax { get; set; }
        public Nullable<decimal> NetAmt { get; set; }
    }
}
