//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesItemTaxDetail
    {
        public int STaxID { get; set; }
        public Nullable<int> SHID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string TaxOption { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<int> Shopid { get; set; }
    }
}
