//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonLogin
    {
        public int salon_login_id { get; set; }
        public string Salon_id { get; set; }
        public string Salon_password { get; set; }
        public Nullable<System.TimeSpan> salon_login_time { get; set; }
        public string browser { get; set; }
        public string os { get; set; }
        public string ip_address { get; set; }
    }
}
