//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class salon_Offers
    {
        public int fabkut_offer_id { get; set; }
        public Nullable<int> fabkut_offer_type_id { get; set; }
        public string fabkut_offer_code { get; set; }
        public string fabkut_offer_name { get; set; }
        public string fabkut_offer_desc { get; set; }
        public string fabkut_offer_pic { get; set; }
        public Nullable<System.DateTime> fabkut_offer_start { get; set; }
        public Nullable<System.DateTime> fabkut_offer_end { get; set; }
        public Nullable<int> fabkut_offer_price { get; set; }
        public Nullable<int> fabkut_offer_disc_perc { get; set; }
        public Nullable<int> fabkut_offer_disc_coupon_value { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> decline { get; set; }
        public Nullable<int> business_id { get; set; }
    }
}
