//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot_creation_roster
    {
        public int sloat_creation_roster_id { get; set; }
        public int slot_creation_id { get; set; }
        public Nullable<int> work_place_id { get; set; }
        public int status { get; set; }
        public System.DateTime sloat_creation_roster_date { get; set; }
    }
}
