//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot_master
    {
        public int slot_id { get; set; }
        public Nullable<System.TimeSpan> slot_start { get; set; }
        public Nullable<System.TimeSpan> slot_end { get; set; }
        public string Timeslot { get; set; }
    }
}
