//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxInvoice
    {
        public int TaxInvoiceoid { get; set; }
        public string GSTIN { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public string VoucherNo { get; set; }
        public string GrNo { get; set; }
        public string CompanyMobile { get; set; }
        public string Companyname { get; set; }
        public string CompanyProfile { get; set; }
        public string CompanyAddress { get; set; }
        public string Biller { get; set; }
        public string BillerAddress { get; set; }
        public string BillerGSTIN { get; set; }
        public string BillerSupplyToState { get; set; }
        public string BillerStateCode { get; set; }
        public string Shipper { get; set; }
        public string ShipperGSTIN { get; set; }
        public string ShipperSupplyToState { get; set; }
        public string ShipperStateCode { get; set; }
        public Nullable<int> Sno { get; set; }
        public string Productname { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Unit { get; set; }
        public string RatePerUnit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string IFSCCODE { get; set; }
        public string TermAndCondition { get; set; }
        public Nullable<bool> Shopid { get; set; }
    }
}
