//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class temptable2
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public Nullable<System.TimeSpan> Booking_end_time { get; set; }
        public Nullable<System.DateTime> Booking_date { get; set; }
    }
}
