//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_ProductOrderdetails
    {
        public int product_id { get; set; }
        public Nullable<int> order_amt { get; set; }
        public Nullable<decimal> order_cost { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<System.DateTime> temp_date { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<decimal> billingCost { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<decimal> order_price { get; set; }
        public Nullable<int> business_id { get; set; }
    }
}
