//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_InsertCoordinate
    {
        public int TrackID { get; set; }
        public Nullable<int> UMID { get; set; }
        public string LAT { get; set; }
        public string Long { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
    }
}
