//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> Type_id { get; set; }
        public int activate_by { get; set; }
        public string user_password { get; set; }
        public string email { get; set; }
        public string Contact_no { get; set; }
        public System.DateTime c_date { get; set; }
        public bool active { get; set; }
    }
}
