//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public int Userid { get; set; }
        public Nullable<int> Shopid { get; set; }
        public Nullable<int> Customerid { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Createdate { get; set; }
        public System.DateTime Updatedate { get; set; }
        public string OTP { get; set; }
        public bool IsVerify { get; set; }
        public string CustomerUserID { get; set; }
        public int UserTypeID { get; set; }
        public string DeviceId { get; set; }
        public string ImageURL { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual StoreRegistration StoreRegistration { get; set; }
    }
}
