//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorContract
    {
        public int AutoID { get; set; }
        public int VersionNo { get; set; }
        public int productID { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<decimal> price { get; set; }
        public string Unit { get; set; }
        public string Remark { get; set; }
    
        public virtual Business_Product Business_Product { get; set; }
    }
}
