//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSSEntityFrame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Roaster
    {
        public int w_roaster_id { get; set; }
        public int business_id { get; set; }
        public int work_place_id { get; set; }
        public System.DateTime work_order_date { get; set; }
        public System.TimeSpan work_order_hour { get; set; }
        public System.TimeSpan work_order_min { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
